version: "3.9"
services:

  mysql:
    image: jark/mysql-example:0.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456

networks:
  default:
    name: zero-to-hero
    external: true